permalink: /:categories/:title
relative_permalinks: true
url: http://RicardoSampayo.com
pygments: true
paginate: 3
name: Ricardo Sampayo
markdown: maruku
pygments: true
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

# category_dir: /blog/categories