permalink: /:categories/:title
relative_permalinks: true
url: http://sampayo.github.io/
pygments: true
paginate_path: 'page:num'
paginate: 10
name: Ricardo Sampayo
markdown: maruku
pygments: true

lang: "en"

# category_dir: /blog/categories