permalink: /:categories/:title
relative_permalinks: true
url: http://ricardosampayo.com/
pygments: true
# paginate: 2
paginate_path: "/:categories/page:num" 
name: Ricardo Sampayo
markdown: maruku
pygments: true

# category_dir: /blog/categories